sonar.projectKey=advprog-2026-A15-project_yomu-frontend
sonar.organization=advprog-2026-a15-project
sonar.host.url=https://sonarcloud.io

# Source and test paths
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.js,src/**/*.test.jsx,src/**/*.spec.js,src/**/*.spec.jsx

# Coverage report
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclusions
sonar.exclusions=node_modules/**,dist/**,coverage/**,public/**
